### ISSUE TITLE
Dotnet.exe crashes when using Impersonation

### ISSUE THREAD

**Issue by jjverhage** [novaworksau/Impersonate#1]
Hi Jonathan,

In my .NET Core application, I need to use impersonation. I was very happy to find this middleware!
But when I try it, the dotnet.exe proces crashes.

The steps to reproduce it are:
1. Create a new project in Visual Studio 2017 (ASP.NET Core Web Application (.NET Core))
2. Add this Middleware
3. Turn off "Enable Anonymous Authentication"
4. Turn on "Enable Windows Authentication"
5. Start debugging
6. Application crashes

Could you please help me with it?

Thanks,
Jaap

**Comment by jruckert** [comment]
Can you provide your startup.cs or project.json please?

**Comment by jjverhage** [comment]
The content of the startup.cs:

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Impersonate.AspNetCore.Windows;

namespace WebApplication1
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }


            app.UseStaticFiles();

            app.UseWindowsImpersonation(null);            

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
`

**Comment by jruckert** [comment]
Try using  

`app.UseWindowsImpersonation(options => options.Enabled = true);

**Comment by jjverhage** [comment]
Hi Jonathan,

Now it works for me. Thanks for your excellent help!

Jaap
