### ISSUE TITLE
Please take this code down, it doesn't work

### ISSUE THREAD

**Issue by Tratcher** [novaworksau/Impersonate#4]
RunImpersonated is synchronous, it can't be used for async Tasks. You're starting an asynchronous operation within RunImpersonated and then returning the Task. Exiting RunImpersonated revokes the impersonation and can cause errors or reverting to the base identity in the Task. It appears to work so long as the code downstream remains synchronous, but it breaks as soon as there's an async transition.

There is no proper async version of RunImpersonated, see https://github.com/dotnet/corefx/issues/24977

**Comment by jruckert** [comment]
Agree with what you are saying, but there is no other viable solution for us. I am more than happy to take it down once your related issue is resolved.
